version: '3.1'

volumes:
  db_data:
    driver: local

services:
  db:
    image: mysql/mysql-server:8.0
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: EatWhat
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
        - 8080:80
    environment:
        - PMA_ARBITRARY=1
